[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir=false
fs_permissions = [
    { access = "read-write", path = "./"},
]
ffi=true
auto_detect_remappings = true
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@ccip/=lib/chainlink-local/lib/ccip/",
    "@chainlink-local/=lib/chainlink-local/",
    "@murky/=lib/murky/",
    "foundry-devops/=lib/foundry-devops",
    "@oz/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/"
]
etherscan_api_key="${ETHERSCAN_API_KEY}"
[profile.test]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
arb-sepolia = "${ARB_SEPOLIA_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[invariant]
runs = 1000
depth = 128
fail_on_revert = false